package au.org.paperminer.model;

// Generated Aug 21, 2013 12:00:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * PmAdmins generated by hbm2java
 */
@JsonAutoDetect
@Entity
@Table(name = "pm_admins", catalog = "paperminer")
public class PmAdmins implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6818787878943736618L;
	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "pmUsers"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "user_id", unique = true, nullable = false)
	private int userId;
	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	private PmUsers pmUsers;
	@Column(name = "is_primary", nullable = false)
	private byte isPrimary;
	@Temporal(TemporalType.DATE)
	@Column(name = "date_created", nullable = false, length = 10)
	@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="dd-MM-yyyy")
	private Date dateCreated;

	public PmAdmins() {
	}

	public PmAdmins(PmUsers pmUsers, byte isPrimary, Date dateCreated) {
		this.pmUsers = pmUsers;
		this.isPrimary = isPrimary;
		this.dateCreated = dateCreated;
	}

	
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@JsonIgnore
	public PmUsers getPmUsers() {
		return this.pmUsers;
	}

	public void setPmUsers(PmUsers pmUsers) {
		this.pmUsers = pmUsers;
	}

	
	public byte getIsPrimary() {
		return this.isPrimary;
	}

	public void setIsPrimary(byte isPrimary) {
		this.isPrimary = isPrimary;
	}


	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

}
