package au.org.paperminer.model;

// Generated Aug 21, 2013 12:00:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PmCcodes generated by hbm2java
 */
@Entity
@Table(name = "pm_ccodes", catalog = "paperminer")
public class PmCcodes implements java.io.Serializable {

	private short id;
	private String shortName;
	private String longName;

	public PmCcodes() {
	}

	public PmCcodes(short id, String longName) {
		this.id = id;
		this.longName = longName;
	}

	public PmCcodes(short id, String shortName, String longName) {
		this.id = id;
		this.shortName = shortName;
		this.longName = longName;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public short getId() {
		return this.id;
	}

	public void setId(short id) {
		this.id = id;
	}

	@Column(name = "short_name", length = 2)
	public String getShortName() {
		return this.shortName;
	}

	public void setShortName(String shortName) {
		this.shortName = shortName;
	}

	@Column(name = "long_name", nullable = false, length = 64)
	public String getLongName() {
		return this.longName;
	}

	public void setLongName(String longName) {
		this.longName = longName;
	}

}
