package au.org.paperminer.model;

// Generated Aug 21, 2013 12:00:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PmQueries generated by hbm2java
 */
@Entity
@Table(name = "pm_queries", catalog = "paperminer")
public class PmQueries implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2579020120012467027L;
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	private PmUsers pmUsers;
	@Column(name = "query", nullable = false, length = 256)
	private String query;
	@Column(name = "descr", nullable = false, length = 60)
	private String descr;
	@Column(name = "query_type", nullable = false, length = 1)
	private String queryType;
	@Column(name = "total_last_run", nullable = false)
	private Integer totalLastRun;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_last_run", length = 19)
	private Date dateLastRun;
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", nullable = false, length = 19)
	private Date dateCreated;

	public PmQueries() {
	}

	public PmQueries(PmUsers pmUsers, String query, String descr,
			String queryType, Integer totalLastRun, Date dateCreated) {
		this.pmUsers = pmUsers;
		this.query = query;
		this.descr = descr;
		this.queryType = queryType;
		this.totalLastRun = totalLastRun;
		this.dateCreated = dateCreated;
	}

	public PmQueries(PmUsers pmUsers, String query, String descr,
			String queryType, Integer totalLastRun, Date dateLastRun, Date dateCreated) {
		this.pmUsers = pmUsers;
		this.query = query;
		this.descr = descr;
		this.queryType = queryType;
		this.totalLastRun = totalLastRun;
		this.dateLastRun = dateLastRun;
		this.dateCreated = dateCreated;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public PmUsers getPmUsers() {
		return this.pmUsers;
	}

	public void setPmUsers(PmUsers pmUsers) {
		this.pmUsers = pmUsers;
	}

	public String getQuery() {
		return this.query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	public String getQueryType() {
		return this.queryType;
	}

	public void setQueryType(String queryType) {
		this.queryType = queryType;
	}

	public int getTotalLastRun() {
		return this.totalLastRun;
	}

	public void setTotalLastRun(int totalLastRun) {
		this.totalLastRun = totalLastRun;
	}

	public Date getDateLastRun() {
		return this.dateLastRun;
	}

	public void setDateLastRun(Date dateLastRun) {
		this.dateLastRun = dateLastRun;
	}

	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

}
