package au.org.paperminer.model;

// Generated Aug 21, 2013 12:00:35 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PmTmpLoc generated by hbm2java
 */
@Entity
@Table(name = "pm_tmp_loc", catalog = "paperminer")
public class PmTmpLoc implements java.io.Serializable {

	private PmTmpLocId id;
	private BigDecimal latitude;
	private BigDecimal longitude;
	private BigDecimal boxNwLat;
	private BigDecimal boxNwLng;
	private BigDecimal boxSeLat;
	private BigDecimal boxSeLng;

	public PmTmpLoc() {
	}

	public PmTmpLoc(PmTmpLocId id, BigDecimal latitude, BigDecimal longitude) {
		this.id = id;
		this.latitude = latitude;
		this.longitude = longitude;
	}

	public PmTmpLoc(PmTmpLocId id, BigDecimal latitude, BigDecimal longitude,
			BigDecimal boxNwLat, BigDecimal boxNwLng, BigDecimal boxSeLat,
			BigDecimal boxSeLng) {
		this.id = id;
		this.latitude = latitude;
		this.longitude = longitude;
		this.boxNwLat = boxNwLat;
		this.boxNwLng = boxNwLng;
		this.boxSeLat = boxSeLat;
		this.boxSeLng = boxSeLng;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "name", column = @Column(name = "name", nullable = false, length = 64)),
			@AttributeOverride(name = "stateCode", column = @Column(name = "state_code", nullable = false)),
			@AttributeOverride(name = "countryCode", column = @Column(name = "country_code", nullable = false)) })
	public PmTmpLocId getId() {
		return this.id;
	}

	public void setId(PmTmpLocId id) {
		this.id = id;
	}

	@Column(name = "latitude", nullable = false, precision = 12, scale = 9)
	public BigDecimal getLatitude() {
		return this.latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", nullable = false, precision = 12, scale = 9)
	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	@Column(name = "box_nw_lat", precision = 12, scale = 9)
	public BigDecimal getBoxNwLat() {
		return this.boxNwLat;
	}

	public void setBoxNwLat(BigDecimal boxNwLat) {
		this.boxNwLat = boxNwLat;
	}

	@Column(name = "box_nw_lng", precision = 12, scale = 9)
	public BigDecimal getBoxNwLng() {
		return this.boxNwLng;
	}

	public void setBoxNwLng(BigDecimal boxNwLng) {
		this.boxNwLng = boxNwLng;
	}

	@Column(name = "box_se_lat", precision = 12, scale = 9)
	public BigDecimal getBoxSeLat() {
		return this.boxSeLat;
	}

	public void setBoxSeLat(BigDecimal boxSeLat) {
		this.boxSeLat = boxSeLat;
	}

	@Column(name = "box_se_lng", precision = 12, scale = 9)
	public BigDecimal getBoxSeLng() {
		return this.boxSeLng;
	}

	public void setBoxSeLng(BigDecimal boxSeLng) {
		this.boxSeLng = boxSeLng;
	}

}
