package au.org.paperminer.model;

// Generated Aug 21, 2013 12:00:35 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PmTmpLocId generated by hbm2java
 */
@Embeddable
public class PmTmpLocId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1631346516135005148L;
	private String name;
	private Integer stateCode;
	private Integer countryCode;

	public PmTmpLocId() {
	}

	public PmTmpLocId(String name, Integer stateCode, Integer countryCode) {
		this.name = name;
		this.stateCode = stateCode;
		this.countryCode = countryCode;
	}

	@Column(name = "name", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "state_code", nullable = false)
	public Integer getStateCode() {
		return this.stateCode;
	}

	public void setStateCode(Integer stateCode) {
		this.stateCode = stateCode;
	}

	@Column(name = "country_code", nullable = false)
	public Integer getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(Integer countryCode) {
		this.countryCode = countryCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PmTmpLocId))
			return false;
		PmTmpLocId castOther = (PmTmpLocId) other;

		return ((this.getName() == castOther.getName()) || (this.getName() != null
				&& castOther.getName() != null && this.getName().equals(
				castOther.getName())))
				&& (this.getStateCode() == castOther.getStateCode())
				&& (this.getCountryCode() == castOther.getCountryCode());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + this.getStateCode();
		result = 37 * result + this.getCountryCode();
		return result;
	}

}
