package au.org.paperminer.model;

// Generated Aug 21, 2013 12:00:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PmUsers generated by hbm2java
 */
@Entity
@Table(name = "pm_users", catalog = "paperminer")
public class PmUsers implements java.io.Serializable {

	private Integer id;
	private String email;
	private String troveKey;
	private byte status;
	private byte maxQueries;
	private byte maxScheduled;
	private short ttlDays;
	private Date dateCreated;
	private PmAdmins pmAdmins;
	private Set pmQuerieses = new HashSet(0);

	public PmUsers() {
	}

	public PmUsers(String email, String troveKey, byte status, byte maxQueries,
			byte maxScheduled, short ttlDays, Date dateCreated) {
		this.email = email;
		this.troveKey = troveKey;
		this.status = status;
		this.maxQueries = maxQueries;
		this.maxScheduled = maxScheduled;
		this.ttlDays = ttlDays;
		this.dateCreated = dateCreated;
	}

	public PmUsers(String email, String troveKey, byte status, byte maxQueries,
			byte maxScheduled, short ttlDays, Date dateCreated,
			PmAdmins pmAdmins, Set pmQuerieses) {
		this.email = email;
		this.troveKey = troveKey;
		this.status = status;
		this.maxQueries = maxQueries;
		this.maxScheduled = maxScheduled;
		this.ttlDays = ttlDays;
		this.dateCreated = dateCreated;
		this.pmAdmins = pmAdmins;
		this.pmQuerieses = pmQuerieses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "email", nullable = false, length = 60)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "trove_key", nullable = false, length = 20)
	public String getTroveKey() {
		return this.troveKey;
	}

	public void setTroveKey(String troveKey) {
		this.troveKey = troveKey;
	}

	@Column(name = "status", nullable = false)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Column(name = "max_queries", nullable = false)
	public byte getMaxQueries() {
		return this.maxQueries;
	}

	public void setMaxQueries(byte maxQueries) {
		this.maxQueries = maxQueries;
	}

	@Column(name = "max_scheduled", nullable = false)
	public byte getMaxScheduled() {
		return this.maxScheduled;
	}

	public void setMaxScheduled(byte maxScheduled) {
		this.maxScheduled = maxScheduled;
	}

	@Column(name = "ttl_days", nullable = false)
	public short getTtlDays() {
		return this.ttlDays;
	}

	public void setTtlDays(short ttlDays) {
		this.ttlDays = ttlDays;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_created", nullable = false, length = 10)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "pmUsers")
	public PmAdmins getPmAdmins() {
		return this.pmAdmins;
	}

	public void setPmAdmins(PmAdmins pmAdmins) {
		this.pmAdmins = pmAdmins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pmUsers")
	public Set getPmQuerieses() {
		return this.pmQuerieses;
	}

	public void setPmQuerieses(Set pmQuerieses) {
		this.pmQuerieses = pmQuerieses;
	}

}
