package au.org.paperminer.model;

// Generated Aug 21, 2013 12:00:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PmUsers generated by hbm2java
 */
@Entity
@Table(name = "pm_users", catalog = "paperminer")
public class PmUsers implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7295026445975579880L;
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	@Column(name = "email", nullable = false, length = 60)
	private String email;
	@Column(name = "trove_key", nullable = false, length = 20)
	private String troveKey;
	@Column(name = "status", nullable = false)
	private Integer status;
	@Column(name = "max_queries", nullable = false)
	private Integer maxQueries;
	@Column(name = "max_scheduled", nullable = false)
	private Integer maxScheduled;
	@Column(name = "ttl_days", nullable = false)
	private Integer ttlDays;
	@Temporal(TemporalType.DATE)
	@Column(name = "date_created", nullable = false, length = 10)
	private Date dateCreated;
	@OneToOne(fetch = FetchType.LAZY, mappedBy = "pmUsers")
	private PmAdmins pmAdmins;
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pmUsers")
	private List<PmQueries> pmQuerieses;

	public PmUsers() {
	}

	public PmUsers(String email, String troveKey, Integer status, Integer maxQueries,
			Integer maxScheduled, Integer ttlDays, Date dateCreated) {
		this.email = email;
		this.troveKey = troveKey;
		this.status = status;
		this.maxQueries = maxQueries;
		this.maxScheduled = maxScheduled;
		this.ttlDays = ttlDays;
		this.dateCreated = dateCreated;
	}

	public PmUsers(String email, String troveKey, Integer status, Integer maxQueries,
			Integer maxScheduled, Integer ttlDays, Date dateCreated,
			PmAdmins pmAdmins, List<PmQueries> pmQuerieses) {
		this.email = email;
		this.troveKey = troveKey;
		this.status = status;
		this.maxQueries = maxQueries;
		this.maxScheduled = maxScheduled;
		this.ttlDays = ttlDays;
		this.dateCreated = dateCreated;
		this.pmAdmins = pmAdmins;
		this.pmQuerieses = pmQuerieses;
	}

	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	
	public String getTroveKey() {
		return this.troveKey;
	}

	public void setTroveKey(String troveKey) {
		this.troveKey = troveKey;
	}

	
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	
	public Integer getMaxQueries() {
		return this.maxQueries;
	}

	public void setMaxQueries(Integer maxQueries) {
		this.maxQueries = maxQueries;
	}

	
	public Integer getMaxScheduled() {
		return this.maxScheduled;
	}

	public void setMaxScheduled(Integer maxScheduled) {
		this.maxScheduled = maxScheduled;
	}

	
	public Integer getTtlDays() {
		return this.ttlDays;
	}

	public void setTtlDays(Integer ttlDays) {
		this.ttlDays = ttlDays;
	}

	
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	
	public PmAdmins getPmAdmins() {
		return this.pmAdmins;
	}

	public void setPmAdmins(PmAdmins pmAdmins) {
		this.pmAdmins = pmAdmins;
	}

	
	public List<PmQueries> getPmQuerieses() {
		return this.pmQuerieses;
	}

	public void setPmQuerieses(List<PmQueries> pmQuerieses) {
		this.pmQuerieses = pmQuerieses;
	}

}
